[package]
name = "task_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
event_macro = { path = "./event_macro" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
serde_json = "1.0"
serde_yaml = "0.9"
once_cell = "1.17"
walkdir = "2.3"

